server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/tours {
        proxy_pass https://api-travel.agenteviajes.com/v1/integracion/tours;
        proxy_ssl_server_name on;
        proxy_set_header Host api-travel.agenteviajes.com;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Cache-Control "public, max-age=300";
    }

    location /i/ {
        proxy_pass https://api-travel.agenteviajes.com/i/;
        proxy_ssl_server_name on;
        proxy_set_header Host api-travel.agenteviajes.com;
        proxy_hide_header Cross-Origin-Resource-Policy;
        add_header Cross-Origin-Resource-Policy cross-origin;
        add_header Cache-Control "public, max-age=86400";
    }
}
